name: Style check

on: push

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Rubocop checks
        uses: gimenete/rubocop-action@1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
